# VirtualBox guest — NixOS
# Imports shared modules then adds only what is unique to this machine.
{ ... }:
{
  imports = [
    ./hardware-configuration.nix # generated by nixos-generate-config
    ./vboxsf.nix
    ../../modules/shared/nix-settings.nix
    ../../modules/shared/locale.nix
    ../../modules/nixos/common.nix
    ../../modules/nixos/users.nix
    ../../modules/nixos/virtualbox-guest.nix
  ];

  networking.hostName = "nixos-vbox";

  # Standard EFI bootloader — correct for VirtualBox EFI installs
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Set once at first install — do not change afterwards
  system.stateVersion = "25.11";
}
